#ifndef MQTTDEFINITIONS_H
#define MQTTDEFINITIONS_H

enum msg_type_e
{
    RESERVED_MSG_TYPE = 0,
    CONNECT = 1,
    CONNACK = 2,
    PUBLISH = 3,
    PUBACK = 4,
    PUBREC = 5,
    PUBREL = 6,
    PUBCOMP = 7,
    SUBSCRIBE = 8,
    SUBACK = 9,
    UNSUBSCRIBE = 10,
    UNSUBACK = 11,
    PINGREQ = 12,
    PINGRESP = 13,
    DISCONNECT = 14
};

enum qos_e
{
    AT_MOST_ONCE = 0,
    AT_LEAST_ONCE = 1,
    EXACTLY_ONCE = 2,
    RESERVED_QOS = 3
};

enum connect_return_code_e
{
    CONNECTION_ACCEPTED = 0,
    UNACCEPTABLE_PROTOCOL_VERSION = 1,
    IDENTIFIER_REJECTED = 2,
    SERVER_UNAVAILABLE = 3,
    BAD_USERNAME_OR_PASSWORD = 4,
    NOT_AUTHORIZED = 5,
    RESERVED_CONNECT_RETURN_CODE = 6
};

#define MAX_LENGTH_PUB_VAR_HEADER 256
#define MAX_SIZE_PUB_MSG 512

#define MAX_SUB_PAYLOAD_SIZE 256

#define MQTT_VAR_HEADER_SIZE 12

#endif // MQTTDEFINITIONS_H